fix enrichmentAnalysis.
it fails on line 126 with error below.

Error: AttributeError: 'DataFrame' object has no attribute 'sort'

The sort method has been removed & replaced with sort_values in newer versions of Pandas DataFrame so we use that one instead.

Signed-off-by: Mustafa Nural <mvnural@gmail.com>